### ISSUE TITLE
Error while migrating from Redis 3.0.* to 3.2.*

### ISSUE THREAD

**Issue by iDhruv22** [gosquared/redis-clustr#12]
RedisClustr.js:238
if (c.ready) {
              ^
TypeError: Cannot read property 'ready' of undefined

**Comment by jbt** [comment]
Thanks for the report @iDhruv22! This will be due to the chane in redis's output for `CLUSTER SLOTS` to now include the node id as well as the IP and port. We'll get a patch put together.

**Comment by jbt** [comment]
I've put together #13 which should fix this issue - holding off on publishing to npm just until I can sort out my own testing setup with 3.2 and make sure there's nothing else I've missed. So if you want to / are able to, then feel free to try that out and see if it works for you.

**Comment by iDhruv22** [comment]
Okay sure. I'll try and let you know. Thanks, James.

**Comment by jbt** [comment]
Just published v1.5.1 to npm with the fix
